# Generated by Django 5.2.8 on 2025-11-25 22:39

import django.db.models.deletion
import myapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakalavrCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MagistratCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bakalavr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kunduzgi_kvota', models.IntegerField(validators=[myapp.validators.validate_non_negative])),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bakalavrlar', to='myapp.bakalavrcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Magistr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kunduzgi_kvota', models.IntegerField(validators=[myapp.validators.validate_non_negative])),
                ('kategorya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magistrlar', to='myapp.magistratcategory')),
            ],
        ),
    ]
