# Generated by Django 5.2.8 on 2025-11-26 08:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Yo'nalish nomi")),
            ],
            options={
                'verbose_name': "Yo'nalish Kategoriyasi",
                'verbose_name_plural': "Yo'nalish Kategoriyalari",
            },
        ),
        migrations.CreateModel(
            name='QabulApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH (Familiya, Ism, Otasining ismi)')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefon raqam formati noto‘g‘ri! Masalan: +998901234567', regex='^\\+?\\d{9,15}$')], verbose_name='Telefon raqami')),
                ('address', models.CharField(max_length=255, verbose_name='Yashash manzilingiz')),
                ('education', models.CharField(choices=[('orta_maxsus', "O'rta maxsus"), ('oliy', 'Oliy'), ('boshqa', 'Boshqa')], max_length=20, verbose_name="Qaysi o'qishni tugatgansiz")),
                ('language_level', models.CharField(choices=[('boshlangich', "Boshlang'ich"), ('orta', "O'rta"), ('yuqori', 'Yuqori'), ('ona_tili', 'Ona tili')], max_length=20, verbose_name='Til bilish darajasi')),
                ('diploma', models.FileField(upload_to='documents/diploma/', verbose_name='Shahodatnoma yoki diplom')),
                ('id_card', models.FileField(upload_to='documents/id_card/', verbose_name='ID karta yoki pasport')),
                ('parent_passport', models.FileField(upload_to='documents/parent_passport/', verbose_name='Ota yoki onasi pasporti')),
                ('photo_3x4', models.ImageField(upload_to='photos/3x4/', verbose_name='3x4 rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.qabulcategory', verbose_name="Yo'nalish kategoriyasi")),
            ],
            options={
                'verbose_name': 'Qabul arizasi',
                'verbose_name_plural': 'Qabul arizalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
