# Generated by Django 5.2.8 on 2025-11-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_qabulcategory_qabulapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='qabulapplication',
            name='direction',
            field=models.CharField(default='a', max_length=255, verbose_name="Yo'nalish"),
            preserve_default=False,
        ),
    ]
