# Generated by Django 5.2.8 on 2025-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_qabulapplication_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabulapplication',
            name='photo_3x4',
            field=models.FileField(upload_to='photos/3x4/', verbose_name='3x4 rasm'),
        ),
    ]
