# Generated by Django 5.2.8 on 2025-11-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_qabulapplication_photo_3x4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qabulapplication',
            name='direction',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Yo'nalish"),
        ),
    ]
