# Generated by Django 5.2.8 on 2025-12-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_qabulapplication_direction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qabulapplication',
            options={'ordering': ['id'], 'verbose_name': 'Qabul arizasi', 'verbose_name_plural': 'Qabul arizalari'},
        ),
        migrations.AddField(
            model_name='qabulapplication',
            name='is_published',
            field=models.BooleanField(blank=True, null=True, verbose_name='chop etish'),
        ),
    ]
