# Generated by Django 5.0.7 on 2025-06-16 09:57

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Yonalish')),
            ],
            options={
                'verbose_name': 'Yonalish kiriting',
                'verbose_name_plural': 'Yonalish Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Till',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='til bilish daraja')),
            ],
            options={
                'verbose_name': 'til bilish daraja',
                'verbose_name_plural': 'til bilish daraja',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.SH')),
                ('files', models.FileField(upload_to='files/', verbose_name='shahodatnoma yoki diplom')),
                ('pasport', models.FileField(upload_to='files/', verbose_name='ota yoki onasi pasporti')),
                ('photo', models.ImageField(upload_to='files_photo', verbose_name='3x4 rasim')),
                ('shaxar', models.CharField(max_length=350, verbose_name='yashash manzilingiz')),
                ('number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Telefon raqami')),
                ('education', models.CharField(max_length=150, verbose_name="Qaysi O'qishni tugatgansiz")),
                ('userFan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.education', verbose_name="Yo'nalishni tanlang")),
                ('userTill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.till', verbose_name='Fanni tanlang')),
            ],
            options={
                'verbose_name': "Ro'yxatdan o'tganlar",
                'verbose_name_plural': "Ro'yxatdan o'tganlar",
            },
        ),
    ]
