# Generated by Django 5.0.7 on 2025-06-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='id_card',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='ID-karta yoki pasport'),
        ),
    ]
