# Generated by Django 5.0.7 on 2025-06-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usermodel_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
