# Generated by Django 5.0.7 on 2025-06-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_usermodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
