# Generated by Django 5.2.3 on 2025-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_usermodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='files',
            field=models.ImageField(upload_to='files/', verbose_name='shahodatnoma yoki diplom'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id_card',
            field=models.ImageField(blank=True, upload_to='files/', verbose_name='ID-karta yoki pasport'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pasport',
            field=models.ImageField(upload_to='files/', verbose_name='ota yoki onasi pasporti'),
        ),
    ]
