# Generated by Django 5.2 on 2025-11-24 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_usermodel_files_alter_usermodel_id_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QabulHolati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(blank=True, default='Online Qabul', max_length=100, null=True, verbose_name='Qabul turi')),
                ('ochiq', models.BooleanField(blank=True, default=True, null=True, verbose_name='Qabul ochiqmi?')),
                ('xabar', models.TextField(blank=True, default="Online qabul tugallandi. Hujjat topshirish istagida bo'lganlar Sambhram NTM qabul komissiyasiga murojaat qilishlarini so'raymiz.", null=True, verbose_name="Yopiq holatda ko'rsatiladigan xabar")),
            ],
            options={
                'verbose_name': 'Qabul holati',
                'verbose_name_plural': 'Qabul holati',
            },
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='files',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])], verbose_name='shahodatnoma yoki diplom'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id_card',
            field=models.FileField(blank=True, upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])], verbose_name='ID-karta yoki pasport'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pasport',
            field=models.FileField(upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg'])], verbose_name='ota yoki onasi pasporti'),
        ),
    ]
